spring.application.name=pagamentos-ms

# datasources
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${MYSQL_DB_URL}
spring.datasource.username=${MYSQL_DB_USERNAME}
spring.datasource.password=${MYSQL_DB_PASSWORD}
spring.jpa.show-sql=true

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka
eureka.instance.instance-id=${spring.application.name}:${random.int}
server.port=0

# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.atualizaPedido.slidingWindowSize: 3
resilience4j.circuitbreaker.instances.atualizaPedido.minimumNumberOfCalls: 2
resilience4j.circuitbreaker.instances.atualizaPedido.waitDurationInOpenState: 50s

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=diogo
spring.rabbitmq.password=diogo






